### ISSUE TITLE
Low NPE issue

### ISSUE THREAD

**Issue by dustyattenborough** [cpnr/ratpac-two#10]
We expect NPE to be approximately equal to the light yield, but the output of the RAT macro shows a much lower value of NPE.

Currently, the NPE at the PMT is approximately 1/500 of the light yield.

Therefore, we need to achieve an NPE of the order of 1000 when the light yield is 10000/MeV.

![image](https://github.com/cpnr/ratpac-two/assets/58801968/4f49f60c-6716-4979-9894-1b0731a985e1)

**Comment by dustyattenborough** [comment]
![image](https://github.com/cpnr/ratpac-two/assets/58801968/9a131ff6-633e-4053-a3f4-f5ac5a246632)

photon 갯수 줄이는 가장 큰 영향은 "QuenchedTotalEnergyDeposit" 으로 보입니다

**Comment by jhgoh** [comment]
이 문제는 geometry 구현에서 hierarchy를 잘못 입력했기 때문인 것으로, https://github.com/cpnr/renesim/pull/91 에서 해결됨.
이 issue는 닫습니다.
