### ISSUE TITLE
Implement ANNRI-Gd model

### ISSUE THREAD

**Issue by jhgoh** [cpnr/ratpac-two#3]
Implement ANNRI-Gd model
 https://github.com/cpnr/renesim/issues/57 https://github.com/cpnr/renesim/issues/54

**Comment by opercjy** [comment]
[src_v2.txt](https://github.com/cpnr/ratpac-two/files/14847146/src_v2.txt)
zip 파일 확장자.
수정한 기능에 대한 간략한 UML 추가 할 예정

**Comment by opercjy** [comment]
Zip 확장자

패치 내용

- [ ] Track 정보에 기반하여 Gd 타켓에 ANNRI 모델 적용하도록 논리 제어 추가
![image](https://github.com/cpnr/ratpac-two/assets/158591410/8765c3ac-f023-442d-8ab6-e0c30ff21d55)
![image](https://github.com/cpnr/ratpac-two/assets/158591410/1f34ae8e-acf4-4781-b048-58428302d1bc)

후속으로 G4NeutronHPCapture.cc 참조하여 Gd 이외에 타켓 원소에는 Geant4 비탄성 상호작용 모델 및 실험 데이터 상속. 

[rat_src_v3.txt](https://github.com/cpnr/ratpac-two/files/14897432/rat_src_v3.txt)

**Comment by jhgoh** [comment]
ANNRI-Gd 모델 구현과 QBBC/MyShielding 추가 부분을 분리해서 처리해도 될 것 같은데 괜찮을까요?

**Comment by jhgoh** [comment]
현재의 nGd 브랜치가 꼭 필요한 파일들만 있어서 읽기는 좋은 편이지만, branch 를 만드시는 과정에서 rat-pac에 PR을 만들 수 없는 구조로 되어 만들어진 것 같습니다. 

지금 만들어진 commit을 ratpac-two main브랜치로 cherry-pick해서 가져온 다음 conflict 수정 해 업데이트 해 두겠습니다.
RENE 브랜치로 merge는  main 브랜치에 merge되도록 만들고 나서 확인 해보겠습니다.

**Comment by jhgoh** [comment]
기존 소스 트리를 포함한 브랜치를 만들었습니다.
https://github.com/cpnr/ratpac-two/tree/ANNRI_Gd_G411 

RENE 브랜치에 merge하거나, 앞으로 개발 상황에 따라 RENE 브랜치를 해당 브랜치쪽으로 merge 또는 rebase해 넣을 수 있게 됩니다.

@opercjy 반대 의견 없으시면 nGd 브랜치는 삭제하려고 합니다. 
@dustyattenborough 추가 설치과정 (dropbox에서 다운로드나 sed로 코드 in-place수정 등) 따로 하지 않고 git clone할 때 -b ANNRI_Gd_G411 브랜치를 가져오도록 지정하면 될 거예요.

**Comment by opercjy** [comment]
어제 철야를 해서 회신이 늦었습니다.

Jira, bitbucket를 다른 실험에서 썻지만, 소스트리를 위주로 써기 때문에 cmd git은 아직 익숙치가 않습니다. 불편을
드려 송구합니다.

넵 그렇게 해주셔서 감사합니다.

최지영 올림

2024년 4월 9일 (화) 오후 9:49, Junghwan John Goh ***@***.***>님이 작성:

**Comment by jhgoh** [comment]
@opercjy 앗 송구하다 하시면 제가 더 죄송하고 감사해요 0.0;;;;

코드 작업하신 내용 대충 따라가 봤더니 일의 양이 많았는데 고생 정말 많으셨어요.

**Comment by jhgoh** [comment]
모델 동작 검증 뒤에 RENE main branch로 merge하는 PR만들고 merge하면 될 것 같습니다.

단, 현재 가져온 ANNRI-Gd 모델 .cc 파일들에 extern 등 전역변수들이 쓰이고 있고, TFile을 열어서 쓰는 부분들이 있어서 refine작업이 필요할지 모르겠습니다.
외부에서 그대로 가져온 코드라면 crash가 나지 않는 한은 일단 원작자가 작성한 형식을 유지해 두어도 괜찮은데, Geant4.11로 porting작업하며 수정한 사항이 있다면 적절히 시간을 두고 modernize해도 괜찮지 않을까 합니다.

**Comment by jhgoh** [comment]
https://github.com/cpnr/renesim/pull/78 을 통해서 현재 구현된 ANNRI 모델을 적용할 수 있는 instruction을 추가 했습니다.

**Comment by jhgoh** [comment]
이전 미팅에서 이야기된 코드 변경사항이 현재 Annri-Gd 브랜치에 적용이 되어 있는게 맞나요?
https://github.com/rat-pac/ratpac-two/compare/main...cpnr:ratpac-two:ANNRI_Gd_G411 
여기에서 6월 2일과 3일 commit이 있는데 이 commit들이 맞을까요?
맞다면 tag 달아두려고 합니다.

**Comment by opercjy** [comment]
이동 중 이라 집에서 최종적으로 다시 확인하고 회신하겠습니다. 감사합니다.
^^

최지영 드림

2024년 6월 17일 (월) 오후 8:42, Junghwan John Goh ***@***.***>님이 작성:

**Comment by opercjy** [comment]
6월 2일 kds는 git global user 정보를 삭제하여 desktop home user 정보로 등록 된 것이고
6월 3일은 git global user 정보를 다시 복원하고 6월 2일 버전 RAT-ANNRI 실행시 Cout 출력 구문을 주석 처리 한 것입니다. 
최지영 드림

**Comment by jhgoh** [comment]
그러면 현재 branch에는 capture time 문제가 해결된 버전이 들어 있는게 맞나요?

**Comment by opercjy** [comment]
맞습니다.

최지영 드림

2024년 6월 17일 (월) 오후 10:44, Junghwan John Goh ***@***.***>님이
작성:

**Comment by jhgoh** [comment]
문제가 해결되었으므로 이 issue 는 close하겠습니다.
덤으로 현재 가장 최신 버전으로 porting했습니다.
